### ISSUE TITLE
Fail to import tasks with depends

### ISSUE THREAD

**Issue by ercpereda** [matthiasbeyer/task-hookrs#27]
```bash
echo '{"description":"This is a task","entry":"20230228T125737Z","status":"pending","uuid":"4e856e3f-33e2-42f5-a8ab-fabcbffba77d","depends":["35079edb-ccec-4492-94bb-e1a35b88fb35"]}' | cargo run

Error: invalid type: sequence, expected a string at line 1 column 134
```

```rust
fn main() -> Result<()> {
    let mut original = String::new();
    io::stdin().read_line(&mut original).unwrap();

    let original_task: Task = import_task(&original).unwrap_or_else(|e| {
        println!("Error: {e}");
        process::exit(1);
    });

    Ok(())
}
```

**Comment by matthiasbeyer** [comment]
Show me your `Cargo.toml` please.

**Comment by ercpereda** [comment]
Thank you  for your fast answer
```toml
[dependencies]
anyhow = "1.0.69"
serde = "1.0.155"
serde_json = "1.0.94"
task-hookrs = "0.8.0"
```
